// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: some.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SomeExample_CreateSomething_FullMethodName = "/payout_proto.SomeExample/CreateSomething"
)

// SomeExampleClient is the client API for SomeExample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SomeExampleClient interface {
	CreateSomething(ctx context.Context, in *SomethingRequest, opts ...grpc.CallOption) (*SomethingResponse, error)
}

type someExampleClient struct {
	cc grpc.ClientConnInterface
}

func NewSomeExampleClient(cc grpc.ClientConnInterface) SomeExampleClient {
	return &someExampleClient{cc}
}

func (c *someExampleClient) CreateSomething(ctx context.Context, in *SomethingRequest, opts ...grpc.CallOption) (*SomethingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SomethingResponse)
	err := c.cc.Invoke(ctx, SomeExample_CreateSomething_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SomeExampleServer is the server API for SomeExample service.
// All implementations must embed UnimplementedSomeExampleServer
// for forward compatibility.
type SomeExampleServer interface {
	CreateSomething(context.Context, *SomethingRequest) (*SomethingResponse, error)
	mustEmbedUnimplementedSomeExampleServer()
}

// UnimplementedSomeExampleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSomeExampleServer struct{}

func (UnimplementedSomeExampleServer) CreateSomething(context.Context, *SomethingRequest) (*SomethingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSomething not implemented")
}
func (UnimplementedSomeExampleServer) mustEmbedUnimplementedSomeExampleServer() {}
func (UnimplementedSomeExampleServer) testEmbeddedByValue()                     {}

// UnsafeSomeExampleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SomeExampleServer will
// result in compilation errors.
type UnsafeSomeExampleServer interface {
	mustEmbedUnimplementedSomeExampleServer()
}

func RegisterSomeExampleServer(s grpc.ServiceRegistrar, srv SomeExampleServer) {
	// If the following call pancis, it indicates UnimplementedSomeExampleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SomeExample_ServiceDesc, srv)
}

func _SomeExample_CreateSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SomethingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeExampleServer).CreateSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SomeExample_CreateSomething_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeExampleServer).CreateSomething(ctx, req.(*SomethingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SomeExample_ServiceDesc is the grpc.ServiceDesc for SomeExample service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SomeExample_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payout_proto.SomeExample",
	HandlerType: (*SomeExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSomething",
			Handler:    _SomeExample_CreateSomething_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "some.proto",
}
